name: CI/CD Pipeline - Vercel Deploy

# Triggers para execução
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Permissões necessárias
permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

# Configurações de concorrência
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Testes e Validações
  test:
    name: Tests & Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
        
      - name: Executar linting
        run: npm run lint
        continue-on-error: true
        
      - name: Build do projeto
        run: npm run build
        
      - name: Verificar tamanho do bundle
        run: |
          echo "📦 Tamanho dos arquivos gerados:"
          du -sh dist/
          ls -la dist/assets/

  # Job 2: Deploy Preview (PRs)
  preview-deploy:
    name: Preview Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: test
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Deploy Preview na Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./

  # Job 3: Deploy Produção
  production-deploy:
    name: Production Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test
    environment:
      name: production
      url: ${{ steps.deploy.outputs.preview-url }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Deploy Produção na Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
          
      - name: Comentar URL de deploy
        uses: actions/github-script@v7
        if: github.event_name == 'push'
        with:
          script: |
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              target_url: '${{ steps.deploy.outputs.preview-url }}',
              description: 'Deploy realizado com sucesso',
              context: 'vercel/deployment'
            })
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4